### ISSUE TITLE
No icons

### ISSUE THREAD

**Issue by cptn-cosmo** [AnalogFeelings/Bluechirp#77]
**Describe the bug:**
I finally managed to build and install this app and i really like it - However it seems that all the icons for the buttons are missing and I don't know why

**To reproduce:**
on a windows 10 machine instal VS 2022, download sourcecode and deploy app
install app and run it

**Expected behavior:**
there should be different icons under each post for the individual actions

**Screenshots:**
![image](https://github.com/AnalogFeelings/Bluechirp/assets/7382310/f185e54e-be37-42e4-917f-388f6420b641)

**System (please complete the following information):**
 - Windows: 10 Pro 22H2 19045.3324
 - App Version: not sure, latest?

**Additional context:**
there also seems to be no menu for settings or something, not sure if there should be, but could also be rlated to this issue?

**Comment by AnalogFeelings** [comment]
This application is designed for Windows 11, it breaks under Windows 10. I'll see if I can do anything once I get back on this project.
