### ISSUE TITLE
Rewrite the app from the ground up.

### ISSUE THREAD

**Issue by AnalogFeelings** [AnalogFeelings/Bluechirp#81]

**Comment by AkazaRenn** [comment]
Hi, I just came up to this project and would like to offer some help. If possible, do you mind sharing some more details under this task and I can try with some?

**Comment by AnalogFeelings** [comment]
> Hi, I just came up to this project and would like to offer some help. If possible, do you mind sharing some more details under this task and I can try with some?

Right now im still trying to make the general skeleton of how the project is gonna be structured so help could end up being a bit chaotic

**Comment by AkazaRenn** [comment]
@AnalogFeelings ah ok. No problem, feel free to let me know when it's ready for some contributions!
